# .github/workflows/crawl_links.yml

name: Crawl Site Links
on:
  schedule:
    - cron: '0 5 * * *'  # 毎日5:00にクローリング（例）
  workflow_dispatch: {}   # 手動実行も可能

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # リポジトリ内容への書き込みを許可（リンクファイルをコミットするため）
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run crawl script
        run: node scripts/crawl_links.js

      - name: Commit crawled links file
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@users.noreply.github.com"
          git add links.json
          git commit -m "Update crawled links [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
