name: Scheduled Twitter Scrape

on:
  schedule:
    # 毎日 09:00 UTC（JST 18:00）に自動実行
    - cron: '0 9 * * *'
  # 手動実行用トリガー
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade git+https://github.com/JustAnotherArchivist/snscrape.git

      - name: Run scraper
        run: python main.py
