name: Test Teams Webhook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Teams Test Script
        run: node scripts/test_teams.js
        env:
          TEAMS_WEBHOOK_URL2: ${{ secrets.TEAMS_WEBHOOK_URL2 }}
