name: Monitor GoogleSearchCentral Tweets to Teams

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # ← 3時間おきに実行

jobs:
  check-for-new-tweets-teams:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run tweet monitoring script for Teams
        run: node scripts/monitor_teams.js
        env:
          TEAMS_WEBHOOK_URL2: ${{ secrets.TEAMS_WEBHOOK_URL2 }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
